Repository codex-team/codex.docs, pull requests merged in 2022-04, with the labels that each got.

#162 use codex bot token for creating new release
  .github/workflows/release-drafter.yml
Labels: chore

#165 Fix docker image build on apple silicon
  docker/Dockerfile.prod
  tsconfig.json
Labels: bug

#168 Use absolute paths for uploads and db
  config/production.json
  docker-compose.yml
  src/backend/app.ts
  src/backend/controllers/transport.ts
  src/backend/models/file.ts
  src/backend/routes/api/transport.ts
  src/backend/utils/database/initDb.ts
  src/backend/views/auth.twig
  src/frontend/js/classes/editor.js
Labels: enhancement

#185 fix critical issue with backward compatibility
  src/backend/utils/crypto.ts
Labels: bug

#170 Password from env variable
  .env.sample
  README.md
  docker-compose.yml
  package.json
  src/backend/app.ts
  src/backend/controllers/transport.ts
  src/backend/controllers/users.ts
  src/backend/models/user.ts
  src/backend/routes/auth.ts
  src/backend/routes/middlewares/token.ts
  src/backend/utils/database/index.ts
  src/generatePassword.ts
  yarn.lock
Labels: enhancement

#186 change docker tag for stage branch
  .github/workflows/build.yml
Labels: chore
